### ISSUE TITLE
Specific Request

### ISSUE THREAD

**Issue by cmwcaelen1** [BarelyFunctionalCode/animation-transmog#18]
This is a bit specific but a friend is trying to make it so they can use a Dragon Axe from their inventory (they don't have the ability to equip it) to chop a tree but have it pull the animation of using a Bronze Axe instead (ID: 879). Would this be possible?

**Comment by BarelyFunctionalCode** [comment]
So you want to use the animation of a bronze axe in place of a dragon axe? I wasn't even aware the dragon axe had a different animation. 

It should be doable. What's the animation ID of the dragon axe?

**Comment by cmwcaelen1** [comment]
Dragon Axe chopping ID is 2846. It's a bit wonky cause she wants to be physically chopping the tree with the Dragon Axe while overriding it with the Bronze Axe one but she can't wield the Dragon Axe, appreciate your help!

**Comment by BarelyFunctionalCode** [comment]
I will take a look and see what I can do. I'll update on this issue once I have something to show.

**Comment by electroslag** [comment]
I actually made an account to add more info here, haha. I am the person who wants this mod.

So basically this is the only mod that has successful transmogged my woodcutting animation while chopping from inventory, all of the settings like "arcane mine" work. I was wondering if it would be too hard to just swap that for the bronze woodcutting animation?  

It plays the animation from the animation player, but as soon as I go to chop it changes back to whatever the woodcutting animation is set to, and I'm assuming default woodcutting overrides it to -1 (instead of what the animation player is playing). I think even just a way to disable all things except the animation player would work for my purposes, I'm a streamer and I'm just trying to troll my chat lmao. 

I know nothing about programming so sorry if this is nonsensical.

**Comment by BarelyFunctionalCode** [comment]
Yeah I can definitely do that by just adding another option to the woodcutting dropdown for "bronze axe" or whatever it would be called. 

Let me take a look and try it out and I'll update here after.

**Comment by BarelyFunctionalCode** [comment]
Commit e9fff2a1a0bf077398575e1321b4f69c10aaab6e addresses this issue.

**Comment by BarelyFunctionalCode** [comment]
Once the above PR has been merged in, the new option will be available in-game. It is called "Bronze Chop".

**Comment by BarelyFunctionalCode** [comment]
As a funny side-note, I was initially confused by your request until I looked at it in game. Only some Animation IDs include the actual graphic it's associated with (aka the bronze axe).

Most actions in-game have separate animations (the movement of the player) and a GFX (the visual associated with the action), but in this specific case, the "bronze axe" animation also includes the visual.

**Comment by electroslag** [comment]
Awesome thank you so much!! And yeah, as a non-programmer the animations seemed very all over the place and I realized when I was trying to do it myself that I was way over my head hahaha. But all of the axes seem to have their own animations, for some reason. Thanks again!

**Comment by BarelyFunctionalCode** [comment]
Yeah no problem. Once the Runelite team reviews and merges the change you can have your fun trolling your viewers. 

Enjoy!
